title: Design using an 8x8 template
hero_image: images/banner.png
description: Design using an 8x8 template
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Design using an 8x8 template
